### ISSUE TITLE
"Error: getTranslators: detection is already running" when localhost web development 

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [zotero/zotero-connectors#435]
I usually have Zotero disabled on localhost when creating a React or Vue app but, when it is enabled, this error appears in the console.
```
caught (in promise) Error: getTranslators: detection is already running
    at Zotero.Translate.Web.<anonymous> (translate.js:1091:45)
    at Zotero.Translate.Web.getTranslators (promise.js:36:17)
    at Object.init (inject.js:106:25)
```

**Comment by asmaloney** [comment]
> do you mean you're navigating to a URL hosted on localhost in a browser with the Connector installed, and when you do, that error appears in the console?

Yes - that's what I was seeing when developing a vue-based site locally (without the Zotero application running), but it doesn't seem to happen all the time? I just fired up everything from scratch (docker, my web app, the browser) and now I'm not seeing it. Maybe it was fixed by something in the latest release (I can't find release notes)?

I will keep an eye on it and add info here if it comes up again.

Or... is there an option to the connector to tell it to turn itself off when browsing localhost?

Thanks @AbeJellinek!
